title: Ursuscamp
email: ryan@ursus.camp
description: >-
  Musings and ramblings. Probably not worth your time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ursuscamp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ursuscamp
github_username:  ursuscamp
domain: ursuscamp.github.io

# Build settings
include: [".well-known", "experiments"]
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge